language: go

env:
  - TEST_RESULTS=/tmp/test-results

script:
  - mkdir -p blddir
  - mkdir -p $TEST_RESULTS
  - env CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o blddir/httpserver .
  - ls -l ./blddir
  - go test -v ./...
  - ./blddir/httpserver &
  - sleep 5
  - curl --retry 10 --retry-delay 1 http://localhost:3000/headers > $TEST_RESULTS/headers.out
  - cat $TEST_RESULTS/headers.out