language: go

env:
  - TEST_RESULTS=/tmp/test-results

script:
  - mkdir -p workdir
  - mkdir -p $TEST_RESULTS
  - go build -o workdir/httpserver .
  - ls -l ./workdir
  - go test -v ./...
  - ./workdir/httpserver &
  - sleep 5
  - curl --retry 10 --retry-delay 1 http://localhost:8090/headers > $TEST_RESULTS/headers.out
  - cat $TEST_RESULTS/headers.out