language: go

env:
  - TEST_RESULTS=/tmp/test-results

script:
  - mkdir -p workdir
  - mkdir -p $TEST_RESULTS
  - go build -o workdir/httpserver .
    chmod o+x workdir/httpserver
  - ls -l ./workdir
  - ./workdir/httpserver &
  - sleep 5
  - curl --retry 10 --retry-delay 1 http://localhost:8090/headers > $TEST_RESULTS/headers.out
  - curl --retry 10 --retry-delay 1 http://localhost:8090/hi > $TEST_RESULTS/hi.out
  - curl --retry 10 --retry-delay 1 http://localhost:8090/hello > $TEST_RESULTS/hello.out
  - cat $TEST_RESULTS/hi.out