FROM golang:alpine3.16 AS build
LABEL maintainer="DC Barringer <nukdcbear@gmail.com>"

RUN wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
RUN chmod a+x /usr/local/bin/yq
WORKDIR /app
COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY *.go ./
RUN go build -o ./httpserver

FROM alpine:3.16

WORKDIR /httpserver
COPY --from=build /app/httpserver ./
COPY config.yaml ./

EXPOSE 3000

ENTRYPOINT [ "/httpserver/httpserver" ]