name: Go

on:
  push:
    branches: [ master ]
    paths-ignore:
      - "!**.cue"
      - "!.github/workflows/build-with-dagger.yml"
  pull_request:
    branches: [ master ]
    paths-ignore:
      - "!**.cue"
      - "!.github/workflows/build-with-dagger.yml"

env:
  TEST_RESULTS: /tmp/test-results

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: |
        mkdir -p blddir
        mkdir -p $TEST_RESULTS
        env CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o blddir/httpserver .
        ls -l ./blddir

    - name: Test
      run: |
        go test -v ./...
        ./blddir/httpserver &
        sleep 5
        curl --retry 10 --retry-delay 1 http://localhost:8090/headers > $TEST_RESULTS/headers.out

    - name: Store headers test results
      uses: actions/upload-artifact@v2
      with:
        name: Test results
        path: ${{ env.TEST_RESULTS }}