name: Go

on:
  push:
    branches: [ master ]
    paths-ignore:
      - "**.cue"
      - ".github/workflows/build-with-dagger.yml"
  pull_request:
    branches: [ master ]
    paths-ignore:
      - "**.cue"
      - ".github/workflows/build-with-dagger.yml"

env:
  TEST_RESULTS: /tmp/test-results

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19

    - name: Build
      run: |
        mkdir -p blddir
        mkdir -p $TEST_RESULTS
        env CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o blddir/httpserver .
        cp config.yaml blddir/
        ls -l ./blddir

    - name: Test
      run: |
        go test -v ./...
        ./blddir/httpserver &
        sleep 5
        curl --retry 10 --retry-delay 1 http://localhost:3000/headers > $TEST_RESULTS/headers.out

    - name: Store headers test results
      uses: actions/upload-artifact@v2
      with:
        name: Test results
        path: ${{ env.TEST_RESULTS }}

    - name: Store build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Build-artifacts
        path: ./blddir

  build-push-image:
    name: build-push-docker-image
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: Build-artifacts
          path: ./blddir

      # setup Docker buld action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/myhttpserver:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/myhttpserver:0.1.0